server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: payment-service

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000

logging:
  level:
    com.example.payment: INFO
    org.springframework: INFO